# Copyright 2020 The MathWorks, Inc.

name: Run MATLAB Tests
description: >-
  Run all tests in a MATLAB project and generate test artifacts. 
  MATLAB includes any files in your project that have a Test label. If your
  pipeline does not leverage a MATLAB project, then MATLAB includes all tests in
  the the root of your repository including its subfolders.
inputs:
  testResultsJUnit:
    description: >-
      JUnit-style test results
      Path to write test results report in JUnit XML format.
    required: true
    default: ""
  codeCoverageCobertura:
    description: >-
      Cobertura code coverage
      Path to write code coverage report in Cobertura XML format.
    required: false
    default: ""
  sourceFolder:
    description: >-
      Source code folder
      Location of the folder containing source code, relative to the project
      root folder. The specified folder and its subfolders are added to the top
      of the MATLAB search path. To generate a code coverage report, MATLAB uses
      only the source code in the specified folder and its subfolders. You can
      specify multiple folders using a colon-separated or a semicolon-separated
      list.
    required: false
    default: ""
runs:
  using: node12
  main: dist/index.js
