name: Build and Test
on: [push]

jobs:
  bat:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Perform npm tasks
        run: npm run ci

      - name: Perform 'setup-matlab'
        uses: matlab-actions/setup-matlab@v0

      - name: Run MATLAB Tests
        uses: ./
        with:
          source-folder: sample
